version: '3.7'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "${GOO_CONTAINER_NAME}"
    ports:
      - "${GOO_CONTAINER_PORT}:${GOO_DB_PORT}"
    environment:
      SA_PASSWORD: "${GOO_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - ./_containers/mssql:/var/opt/mssql
      
